import PDFDocument from "pdfkit";
import { getModel } from "../utils/model.js";
import { uploadToS3 } from "../utils/uploadToS3.js";
import { checkAgentLimit } from "../config/agentRateLimit.js";
import { deductCredits } from "../utils/deductCredits.js";
import { getTextContent } from "../utils/getTextContent.js";

export const pdfAgent = async (state) => {
  try {
    await checkAgentLimit(state.userId, "pdf");
    await deductCredits(state.userId, "pdf");

    const llm = getModel("pdf");

    const aiResponse = await llm.invoke(`
Create a professional document about:

${state.prompt}

Rules:

- Generate a professional title.
- Generate introduction.
- Generate multiple sections.
- Generate bullet points where required.
- Generate conclusion.
- No markdown.
- No code blocks.
- No ** symbols.
- No ### headings.
- Return plain text only.
`);

    const rawContent =
      getTextContent(aiResponse?.content) || state.prompt;

    const lines = rawContent
      .split("\n")
      .filter((line) => line.trim());

    const generatedTitle =
      lines?.[0]?.length < 120 ? lines[0] : state.prompt;

    const cleanContent = rawContent
      .replace(/\*\*/g, "")
      .replace(/```/g, "")
      .replace(/###/g, "")
      .replace(/##/g, "")
      .replace(/#/g, "")
      .trim();

    const fileName = `pdf-${Date.now()}.pdf`;

    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
      bufferPages: true,
      info: {
        Title: generatedTitle,
        Author: "AaryanAI",
        Subject: state.prompt,
        Creator: "AaryanAI PDF Agent",
      },
    });

    const chunks = [];

    const pdfBuffer = await new Promise((resolve, reject) => {
      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      doc
        .fontSize(26)
        .fillColor("#111827")
        .text(generatedTitle, { align: "center" });

      doc.moveDown();

      doc
        .fontSize(10)
        .fillColor("#6B7280")
        .text(`Generated on ${new Date().toLocaleString()}`, {
          align: "center",
        });

      doc.moveDown(3);

      doc
        .fontSize(12)
        .fillColor("#374151")
        .text(cleanContent, {
          align: "left",
          lineGap: 6,
        });

      doc.moveDown(2);

      doc
        .fontSize(10)
        .fillColor("#9CA3AF")
        .text("Generated by AaryanAI", { align: "center" });

      doc.end();
    });

    const downloadUrl = await uploadToS3(
      pdfBuffer,
      fileName,
      "application/pdf"
    );

    return {
      ...state,
      response: `
# ✅ PDF Generated Successfully

📄 **${generatedTitle}**

📥 [Download PDF](${downloadUrl})
`.trim(),
    };
  } catch (error) {
    console.log("PDF Agent Error:", error);

    // Preserve credit / rate-limit errors for the API banner
    if (error?.status) {
      throw error;
    }

    return {
      ...state,
      response: `❌ Failed to generate PDF.${
        error?.message ? ` (${error.message})` : ""
      }`,
    };
  }
};
